/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as adminLayoutRouteImport } from './../../pages/(admin)/layout'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as errors500RouteImport } from './../../pages/(errors)/500'
import { Route as errors404RouteImport } from './../../pages/(errors)/404'
import { Route as errors403RouteImport } from './../../pages/(errors)/403'
import { Route as authLoginOutRouteImport } from './../../pages/(auth)/login-out'
import { Route as authLoginLayoutRouteImport } from './../../pages/(auth)/login/layout'
import { Route as adminTenantLayoutRouteImport } from './../../pages/(admin)/tenant/layout'
import { Route as adminSystemLayoutRouteImport } from './../../pages/(admin)/system/layout'
import { Route as adminMonitorLayoutRouteImport } from './../../pages/(admin)/monitor/layout'
import { Route as authLoginIndexRouteImport } from './../../pages/(auth)/login/index'
import { Route as adminWebsocketTestIndexRouteImport } from './../../pages/(admin)/websocket-test/index'
import { Route as adminTestIndexRouteImport } from './../../pages/(admin)/test/index'
import { Route as adminStreamTestIndexRouteImport } from './../../pages/(admin)/stream-test/index'
import { Route as adminSseTestIndexRouteImport } from './../../pages/(admin)/sse-test/index'
import { Route as adminHomeIndexRouteImport } from './../../pages/(admin)/home/index'
import { Route as authLoginCodeRouteImport } from './../../pages/(auth)/login/code'
import { Route as adminSystemLogLayoutRouteImport } from './../../pages/(admin)/system/log/layout'
import { Route as adminTenantPackageIndexRouteImport } from './../../pages/(admin)/tenant/package/index'
import { Route as adminTenantListIndexRouteImport } from './../../pages/(admin)/tenant/list/index'
import { Route as adminSystemUserIndexRouteImport } from './../../pages/(admin)/system/user/index'
import { Route as adminSystemRoleIndexRouteImport } from './../../pages/(admin)/system/role/index'
import { Route as adminSystemPostIndexRouteImport } from './../../pages/(admin)/system/post/index'
import { Route as adminSystemOssIndexRouteImport } from './../../pages/(admin)/system/oss/index'
import { Route as adminSystemOssConfigIndexRouteImport } from './../../pages/(admin)/system/oss-config/index'
import { Route as adminSystemNoticeIndexRouteImport } from './../../pages/(admin)/system/notice/index'
import { Route as adminSystemMenuIndexRouteImport } from './../../pages/(admin)/system/menu/index'
import { Route as adminSystemDictIndexRouteImport } from './../../pages/(admin)/system/dict/index'
import { Route as adminSystemDeptIndexRouteImport } from './../../pages/(admin)/system/dept/index'
import { Route as adminSystemConfigIndexRouteImport } from './../../pages/(admin)/system/config/index'
import { Route as adminSystemClientIndexRouteImport } from './../../pages/(admin)/system/client/index'
import { Route as adminMonitorOnlineIndexRouteImport } from './../../pages/(admin)/monitor/online/index'
import { Route as adminMonitorCacheIndexRouteImport } from './../../pages/(admin)/monitor/cache/index'
import { Route as adminSystemLogOperlogIndexRouteImport } from './../../pages/(admin)/system/log/operlog/index'
import { Route as adminSystemLogLogininfoIndexRouteImport } from './../../pages/(admin)/system/log/logininfo/index'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginOutRoute = authLoginOutRouteImport.update({
  id: '/(auth)/login-out',
  path: '/login-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginLayoutRoute = authLoginLayoutRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTenantLayoutRoute = adminTenantLayoutRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSystemLayoutRoute = adminSystemLayoutRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminMonitorLayoutRoute = adminMonitorLayoutRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminWebsocketTestIndexRoute = adminWebsocketTestIndexRouteImport.update({
  id: '/websocket-test/',
  path: '/websocket-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminTestIndexRoute = adminTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminStreamTestIndexRoute = adminStreamTestIndexRouteImport.update({
  id: '/stream-test/',
  path: '/stream-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSseTestIndexRoute = adminSseTestIndexRouteImport.update({
  id: '/sse-test/',
  path: '/sse-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminHomeIndexRoute = adminHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginCodeRoute = authLoginCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminSystemLogLayoutRoute = adminSystemLogLayoutRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminTenantPackageIndexRoute = adminTenantPackageIndexRouteImport.update({
  id: '/package/',
  path: '/package/',
  getParentRoute: () => adminTenantLayoutRoute,
} as any)
const adminTenantListIndexRoute = adminTenantListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => adminTenantLayoutRoute,
} as any)
const adminSystemUserIndexRoute = adminSystemUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemRoleIndexRoute = adminSystemRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemPostIndexRoute = adminSystemPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemOssIndexRoute = adminSystemOssIndexRouteImport.update({
  id: '/oss/',
  path: '/oss/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemOssConfigIndexRoute =
  adminSystemOssConfigIndexRouteImport.update({
    id: '/oss-config/',
    path: '/oss-config/',
    getParentRoute: () => adminSystemLayoutRoute,
  } as any)
const adminSystemNoticeIndexRoute = adminSystemNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemMenuIndexRoute = adminSystemMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemDictIndexRoute = adminSystemDictIndexRouteImport.update({
  id: '/dict/',
  path: '/dict/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemDeptIndexRoute = adminSystemDeptIndexRouteImport.update({
  id: '/dept/',
  path: '/dept/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemConfigIndexRoute = adminSystemConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminSystemClientIndexRoute = adminSystemClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => adminSystemLayoutRoute,
} as any)
const adminMonitorOnlineIndexRoute = adminMonitorOnlineIndexRouteImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => adminMonitorLayoutRoute,
} as any)
const adminMonitorCacheIndexRoute = adminMonitorCacheIndexRouteImport.update({
  id: '/cache/',
  path: '/cache/',
  getParentRoute: () => adminMonitorLayoutRoute,
} as any)
const adminSystemLogOperlogIndexRoute =
  adminSystemLogOperlogIndexRouteImport.update({
    id: '/operlog/',
    path: '/operlog/',
    getParentRoute: () => adminSystemLogLayoutRoute,
  } as any)
const adminSystemLogLogininfoIndexRoute =
  adminSystemLogLogininfoIndexRouteImport.update({
    id: '/logininfo/',
    path: '/logininfo/',
    getParentRoute: () => adminSystemLogLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/monitor': typeof adminMonitorLayoutRouteWithChildren
  '/system': typeof adminSystemLayoutRouteWithChildren
  '/tenant': typeof adminTenantLayoutRouteWithChildren
  '/login': typeof authLoginLayoutRouteWithChildren
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/system/log': typeof adminSystemLogLayoutRouteWithChildren
  '/login/code': typeof authLoginCodeRoute
  '/home/': typeof adminHomeIndexRoute
  '/sse-test/': typeof adminSseTestIndexRoute
  '/stream-test/': typeof adminStreamTestIndexRoute
  '/test/': typeof adminTestIndexRoute
  '/websocket-test/': typeof adminWebsocketTestIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/monitor/cache/': typeof adminMonitorCacheIndexRoute
  '/monitor/online/': typeof adminMonitorOnlineIndexRoute
  '/system/client/': typeof adminSystemClientIndexRoute
  '/system/config/': typeof adminSystemConfigIndexRoute
  '/system/dept/': typeof adminSystemDeptIndexRoute
  '/system/dict/': typeof adminSystemDictIndexRoute
  '/system/menu/': typeof adminSystemMenuIndexRoute
  '/system/notice/': typeof adminSystemNoticeIndexRoute
  '/system/oss-config/': typeof adminSystemOssConfigIndexRoute
  '/system/oss/': typeof adminSystemOssIndexRoute
  '/system/post/': typeof adminSystemPostIndexRoute
  '/system/role/': typeof adminSystemRoleIndexRoute
  '/system/user/': typeof adminSystemUserIndexRoute
  '/tenant/list/': typeof adminTenantListIndexRoute
  '/tenant/package/': typeof adminTenantPackageIndexRoute
  '/system/log/logininfo/': typeof adminSystemLogLogininfoIndexRoute
  '/system/log/operlog/': typeof adminSystemLogOperlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/monitor': typeof adminMonitorLayoutRouteWithChildren
  '/system': typeof adminSystemLayoutRouteWithChildren
  '/tenant': typeof adminTenantLayoutRouteWithChildren
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/system/log': typeof adminSystemLogLayoutRouteWithChildren
  '/login/code': typeof authLoginCodeRoute
  '/home': typeof adminHomeIndexRoute
  '/sse-test': typeof adminSseTestIndexRoute
  '/stream-test': typeof adminStreamTestIndexRoute
  '/test': typeof adminTestIndexRoute
  '/websocket-test': typeof adminWebsocketTestIndexRoute
  '/login': typeof authLoginIndexRoute
  '/monitor/cache': typeof adminMonitorCacheIndexRoute
  '/monitor/online': typeof adminMonitorOnlineIndexRoute
  '/system/client': typeof adminSystemClientIndexRoute
  '/system/config': typeof adminSystemConfigIndexRoute
  '/system/dept': typeof adminSystemDeptIndexRoute
  '/system/dict': typeof adminSystemDictIndexRoute
  '/system/menu': typeof adminSystemMenuIndexRoute
  '/system/notice': typeof adminSystemNoticeIndexRoute
  '/system/oss-config': typeof adminSystemOssConfigIndexRoute
  '/system/oss': typeof adminSystemOssIndexRoute
  '/system/post': typeof adminSystemPostIndexRoute
  '/system/role': typeof adminSystemRoleIndexRoute
  '/system/user': typeof adminSystemUserIndexRoute
  '/tenant/list': typeof adminTenantListIndexRoute
  '/tenant/package': typeof adminTenantPackageIndexRoute
  '/system/log/logininfo': typeof adminSystemLogLogininfoIndexRoute
  '/system/log/operlog': typeof adminSystemLogOperlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/(admin)/monitor': typeof adminMonitorLayoutRouteWithChildren
  '/(admin)/system': typeof adminSystemLayoutRouteWithChildren
  '/(admin)/tenant': typeof adminTenantLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginLayoutRouteWithChildren
  '/(auth)/login-out': typeof authLoginOutRoute
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(admin)/system/log': typeof adminSystemLogLayoutRouteWithChildren
  '/(auth)/login/code': typeof authLoginCodeRoute
  '/(admin)/home/': typeof adminHomeIndexRoute
  '/(admin)/sse-test/': typeof adminSseTestIndexRoute
  '/(admin)/stream-test/': typeof adminStreamTestIndexRoute
  '/(admin)/test/': typeof adminTestIndexRoute
  '/(admin)/websocket-test/': typeof adminWebsocketTestIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(admin)/monitor/cache/': typeof adminMonitorCacheIndexRoute
  '/(admin)/monitor/online/': typeof adminMonitorOnlineIndexRoute
  '/(admin)/system/client/': typeof adminSystemClientIndexRoute
  '/(admin)/system/config/': typeof adminSystemConfigIndexRoute
  '/(admin)/system/dept/': typeof adminSystemDeptIndexRoute
  '/(admin)/system/dict/': typeof adminSystemDictIndexRoute
  '/(admin)/system/menu/': typeof adminSystemMenuIndexRoute
  '/(admin)/system/notice/': typeof adminSystemNoticeIndexRoute
  '/(admin)/system/oss-config/': typeof adminSystemOssConfigIndexRoute
  '/(admin)/system/oss/': typeof adminSystemOssIndexRoute
  '/(admin)/system/post/': typeof adminSystemPostIndexRoute
  '/(admin)/system/role/': typeof adminSystemRoleIndexRoute
  '/(admin)/system/user/': typeof adminSystemUserIndexRoute
  '/(admin)/tenant/list/': typeof adminTenantListIndexRoute
  '/(admin)/tenant/package/': typeof adminTenantPackageIndexRoute
  '/(admin)/system/log/logininfo/': typeof adminSystemLogLogininfoIndexRoute
  '/(admin)/system/log/operlog/': typeof adminSystemLogOperlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/monitor'
    | '/system'
    | '/tenant'
    | '/login'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/system/log'
    | '/login/code'
    | '/home/'
    | '/sse-test/'
    | '/stream-test/'
    | '/test/'
    | '/websocket-test/'
    | '/login/'
    | '/monitor/cache/'
    | '/monitor/online/'
    | '/system/client/'
    | '/system/config/'
    | '/system/dept/'
    | '/system/dict/'
    | '/system/menu/'
    | '/system/notice/'
    | '/system/oss-config/'
    | '/system/oss/'
    | '/system/post/'
    | '/system/role/'
    | '/system/user/'
    | '/tenant/list/'
    | '/tenant/package/'
    | '/system/log/logininfo/'
    | '/system/log/operlog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/monitor'
    | '/system'
    | '/tenant'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/system/log'
    | '/login/code'
    | '/home'
    | '/sse-test'
    | '/stream-test'
    | '/test'
    | '/websocket-test'
    | '/login'
    | '/monitor/cache'
    | '/monitor/online'
    | '/system/client'
    | '/system/config'
    | '/system/dept'
    | '/system/dict'
    | '/system/menu'
    | '/system/notice'
    | '/system/oss-config'
    | '/system/oss'
    | '/system/post'
    | '/system/role'
    | '/system/user'
    | '/tenant/list'
    | '/tenant/package'
    | '/system/log/logininfo'
    | '/system/log/operlog'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(admin)/monitor'
    | '/(admin)/system'
    | '/(admin)/tenant'
    | '/(auth)/login'
    | '/(auth)/login-out'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(admin)/system/log'
    | '/(auth)/login/code'
    | '/(admin)/home/'
    | '/(admin)/sse-test/'
    | '/(admin)/stream-test/'
    | '/(admin)/test/'
    | '/(admin)/websocket-test/'
    | '/(auth)/login/'
    | '/(admin)/monitor/cache/'
    | '/(admin)/monitor/online/'
    | '/(admin)/system/client/'
    | '/(admin)/system/config/'
    | '/(admin)/system/dept/'
    | '/(admin)/system/dict/'
    | '/(admin)/system/menu/'
    | '/(admin)/system/notice/'
    | '/(admin)/system/oss-config/'
    | '/(admin)/system/oss/'
    | '/(admin)/system/post/'
    | '/(admin)/system/role/'
    | '/(admin)/system/user/'
    | '/(admin)/tenant/list/'
    | '/(admin)/tenant/package/'
    | '/(admin)/system/log/logininfo/'
    | '/(admin)/system/log/operlog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  authLoginLayoutRoute: typeof authLoginLayoutRouteWithChildren
  authLoginOutRoute: typeof authLoginOutRoute
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-out': {
      id: '/(auth)/login-out'
      path: '/login-out'
      fullPath: '/login-out'
      preLoaderRoute: typeof authLoginOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/tenant': {
      id: '/(admin)/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof adminTenantLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/system': {
      id: '/(admin)/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof adminSystemLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/monitor': {
      id: '/(admin)/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof adminMonitorLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/websocket-test/': {
      id: '/(admin)/websocket-test/'
      path: '/websocket-test'
      fullPath: '/websocket-test/'
      preLoaderRoute: typeof adminWebsocketTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/test/': {
      id: '/(admin)/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof adminTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/stream-test/': {
      id: '/(admin)/stream-test/'
      path: '/stream-test'
      fullPath: '/stream-test/'
      preLoaderRoute: typeof adminStreamTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/sse-test/': {
      id: '/(admin)/sse-test/'
      path: '/sse-test'
      fullPath: '/sse-test/'
      preLoaderRoute: typeof adminSseTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/home/': {
      id: '/(admin)/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof adminHomeIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/code': {
      id: '/(auth)/login/code'
      path: '/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof authLoginCodeRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/system/log': {
      id: '/(admin)/system/log'
      path: '/log'
      fullPath: '/system/log'
      preLoaderRoute: typeof adminSystemLogLayoutRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/tenant/package/': {
      id: '/(admin)/tenant/package/'
      path: '/package'
      fullPath: '/tenant/package/'
      preLoaderRoute: typeof adminTenantPackageIndexRouteImport
      parentRoute: typeof adminTenantLayoutRoute
    }
    '/(admin)/tenant/list/': {
      id: '/(admin)/tenant/list/'
      path: '/list'
      fullPath: '/tenant/list/'
      preLoaderRoute: typeof adminTenantListIndexRouteImport
      parentRoute: typeof adminTenantLayoutRoute
    }
    '/(admin)/system/user/': {
      id: '/(admin)/system/user/'
      path: '/user'
      fullPath: '/system/user/'
      preLoaderRoute: typeof adminSystemUserIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/role/': {
      id: '/(admin)/system/role/'
      path: '/role'
      fullPath: '/system/role/'
      preLoaderRoute: typeof adminSystemRoleIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/post/': {
      id: '/(admin)/system/post/'
      path: '/post'
      fullPath: '/system/post/'
      preLoaderRoute: typeof adminSystemPostIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/oss/': {
      id: '/(admin)/system/oss/'
      path: '/oss'
      fullPath: '/system/oss/'
      preLoaderRoute: typeof adminSystemOssIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/oss-config/': {
      id: '/(admin)/system/oss-config/'
      path: '/oss-config'
      fullPath: '/system/oss-config/'
      preLoaderRoute: typeof adminSystemOssConfigIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/notice/': {
      id: '/(admin)/system/notice/'
      path: '/notice'
      fullPath: '/system/notice/'
      preLoaderRoute: typeof adminSystemNoticeIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/menu/': {
      id: '/(admin)/system/menu/'
      path: '/menu'
      fullPath: '/system/menu/'
      preLoaderRoute: typeof adminSystemMenuIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/dict/': {
      id: '/(admin)/system/dict/'
      path: '/dict'
      fullPath: '/system/dict/'
      preLoaderRoute: typeof adminSystemDictIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/dept/': {
      id: '/(admin)/system/dept/'
      path: '/dept'
      fullPath: '/system/dept/'
      preLoaderRoute: typeof adminSystemDeptIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/config/': {
      id: '/(admin)/system/config/'
      path: '/config'
      fullPath: '/system/config/'
      preLoaderRoute: typeof adminSystemConfigIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/system/client/': {
      id: '/(admin)/system/client/'
      path: '/client'
      fullPath: '/system/client/'
      preLoaderRoute: typeof adminSystemClientIndexRouteImport
      parentRoute: typeof adminSystemLayoutRoute
    }
    '/(admin)/monitor/online/': {
      id: '/(admin)/monitor/online/'
      path: '/online'
      fullPath: '/monitor/online/'
      preLoaderRoute: typeof adminMonitorOnlineIndexRouteImport
      parentRoute: typeof adminMonitorLayoutRoute
    }
    '/(admin)/monitor/cache/': {
      id: '/(admin)/monitor/cache/'
      path: '/cache'
      fullPath: '/monitor/cache/'
      preLoaderRoute: typeof adminMonitorCacheIndexRouteImport
      parentRoute: typeof adminMonitorLayoutRoute
    }
    '/(admin)/system/log/operlog/': {
      id: '/(admin)/system/log/operlog/'
      path: '/operlog'
      fullPath: '/system/log/operlog/'
      preLoaderRoute: typeof adminSystemLogOperlogIndexRouteImport
      parentRoute: typeof adminSystemLogLayoutRoute
    }
    '/(admin)/system/log/logininfo/': {
      id: '/(admin)/system/log/logininfo/'
      path: '/logininfo'
      fullPath: '/system/log/logininfo/'
      preLoaderRoute: typeof adminSystemLogLogininfoIndexRouteImport
      parentRoute: typeof adminSystemLogLayoutRoute
    }
  }
}

interface adminMonitorLayoutRouteChildren {
  adminMonitorCacheIndexRoute: typeof adminMonitorCacheIndexRoute
  adminMonitorOnlineIndexRoute: typeof adminMonitorOnlineIndexRoute
}

const adminMonitorLayoutRouteChildren: adminMonitorLayoutRouteChildren = {
  adminMonitorCacheIndexRoute: adminMonitorCacheIndexRoute,
  adminMonitorOnlineIndexRoute: adminMonitorOnlineIndexRoute,
}

const adminMonitorLayoutRouteWithChildren =
  adminMonitorLayoutRoute._addFileChildren(adminMonitorLayoutRouteChildren)

interface adminSystemLogLayoutRouteChildren {
  adminSystemLogLogininfoIndexRoute: typeof adminSystemLogLogininfoIndexRoute
  adminSystemLogOperlogIndexRoute: typeof adminSystemLogOperlogIndexRoute
}

const adminSystemLogLayoutRouteChildren: adminSystemLogLayoutRouteChildren = {
  adminSystemLogLogininfoIndexRoute: adminSystemLogLogininfoIndexRoute,
  adminSystemLogOperlogIndexRoute: adminSystemLogOperlogIndexRoute,
}

const adminSystemLogLayoutRouteWithChildren =
  adminSystemLogLayoutRoute._addFileChildren(adminSystemLogLayoutRouteChildren)

interface adminSystemLayoutRouteChildren {
  adminSystemLogLayoutRoute: typeof adminSystemLogLayoutRouteWithChildren
  adminSystemClientIndexRoute: typeof adminSystemClientIndexRoute
  adminSystemConfigIndexRoute: typeof adminSystemConfigIndexRoute
  adminSystemDeptIndexRoute: typeof adminSystemDeptIndexRoute
  adminSystemDictIndexRoute: typeof adminSystemDictIndexRoute
  adminSystemMenuIndexRoute: typeof adminSystemMenuIndexRoute
  adminSystemNoticeIndexRoute: typeof adminSystemNoticeIndexRoute
  adminSystemOssConfigIndexRoute: typeof adminSystemOssConfigIndexRoute
  adminSystemOssIndexRoute: typeof adminSystemOssIndexRoute
  adminSystemPostIndexRoute: typeof adminSystemPostIndexRoute
  adminSystemRoleIndexRoute: typeof adminSystemRoleIndexRoute
  adminSystemUserIndexRoute: typeof adminSystemUserIndexRoute
}

const adminSystemLayoutRouteChildren: adminSystemLayoutRouteChildren = {
  adminSystemLogLayoutRoute: adminSystemLogLayoutRouteWithChildren,
  adminSystemClientIndexRoute: adminSystemClientIndexRoute,
  adminSystemConfigIndexRoute: adminSystemConfigIndexRoute,
  adminSystemDeptIndexRoute: adminSystemDeptIndexRoute,
  adminSystemDictIndexRoute: adminSystemDictIndexRoute,
  adminSystemMenuIndexRoute: adminSystemMenuIndexRoute,
  adminSystemNoticeIndexRoute: adminSystemNoticeIndexRoute,
  adminSystemOssConfigIndexRoute: adminSystemOssConfigIndexRoute,
  adminSystemOssIndexRoute: adminSystemOssIndexRoute,
  adminSystemPostIndexRoute: adminSystemPostIndexRoute,
  adminSystemRoleIndexRoute: adminSystemRoleIndexRoute,
  adminSystemUserIndexRoute: adminSystemUserIndexRoute,
}

const adminSystemLayoutRouteWithChildren =
  adminSystemLayoutRoute._addFileChildren(adminSystemLayoutRouteChildren)

interface adminTenantLayoutRouteChildren {
  adminTenantListIndexRoute: typeof adminTenantListIndexRoute
  adminTenantPackageIndexRoute: typeof adminTenantPackageIndexRoute
}

const adminTenantLayoutRouteChildren: adminTenantLayoutRouteChildren = {
  adminTenantListIndexRoute: adminTenantListIndexRoute,
  adminTenantPackageIndexRoute: adminTenantPackageIndexRoute,
}

const adminTenantLayoutRouteWithChildren =
  adminTenantLayoutRoute._addFileChildren(adminTenantLayoutRouteChildren)

interface adminLayoutRouteChildren {
  adminMonitorLayoutRoute: typeof adminMonitorLayoutRouteWithChildren
  adminSystemLayoutRoute: typeof adminSystemLayoutRouteWithChildren
  adminTenantLayoutRoute: typeof adminTenantLayoutRouteWithChildren
  adminHomeIndexRoute: typeof adminHomeIndexRoute
  adminSseTestIndexRoute: typeof adminSseTestIndexRoute
  adminStreamTestIndexRoute: typeof adminStreamTestIndexRoute
  adminTestIndexRoute: typeof adminTestIndexRoute
  adminWebsocketTestIndexRoute: typeof adminWebsocketTestIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminMonitorLayoutRoute: adminMonitorLayoutRouteWithChildren,
  adminSystemLayoutRoute: adminSystemLayoutRouteWithChildren,
  adminTenantLayoutRoute: adminTenantLayoutRouteWithChildren,
  adminHomeIndexRoute: adminHomeIndexRoute,
  adminSseTestIndexRoute: adminSseTestIndexRoute,
  adminStreamTestIndexRoute: adminStreamTestIndexRoute,
  adminTestIndexRoute: adminTestIndexRoute,
  adminWebsocketTestIndexRoute: adminWebsocketTestIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authLoginLayoutRouteChildren {
  authLoginCodeRoute: typeof authLoginCodeRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLoginLayoutRouteChildren: authLoginLayoutRouteChildren = {
  authLoginCodeRoute: authLoginCodeRoute,
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLoginLayoutRouteWithChildren = authLoginLayoutRoute._addFileChildren(
  authLoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  authLoginLayoutRoute: authLoginLayoutRouteWithChildren,
  authLoginOutRoute: authLoginOutRoute,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
