/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as adminLayoutRouteImport } from './../../pages/(admin)/layout'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as errors500RouteImport } from './../../pages/(errors)/500'
import { Route as errors404RouteImport } from './../../pages/(errors)/404'
import { Route as errors403RouteImport } from './../../pages/(errors)/403'
import { Route as authLoginOutRouteImport } from './../../pages/(auth)/login-out'
import { Route as authLoginLayoutRouteImport } from './../../pages/(auth)/login/layout'
import { Route as authLoginIndexRouteImport } from './../../pages/(auth)/login/index'
import { Route as adminWebsocketTestIndexRouteImport } from './../../pages/(admin)/websocket-test/index'
import { Route as adminStreamTestIndexRouteImport } from './../../pages/(admin)/stream-test/index'
import { Route as adminSseTestIndexRouteImport } from './../../pages/(admin)/sse-test/index'
import { Route as adminHomeIndexRouteImport } from './../../pages/(admin)/home/index'
import { Route as authLoginCodeRouteImport } from './../../pages/(auth)/login/code'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginOutRoute = authLoginOutRouteImport.update({
  id: '/(auth)/login-out',
  path: '/login-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginLayoutRoute = authLoginLayoutRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminWebsocketTestIndexRoute = adminWebsocketTestIndexRouteImport.update({
  id: '/websocket-test/',
  path: '/websocket-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminStreamTestIndexRoute = adminStreamTestIndexRouteImport.update({
  id: '/stream-test/',
  path: '/stream-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSseTestIndexRoute = adminSseTestIndexRouteImport.update({
  id: '/sse-test/',
  path: '/sse-test/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminHomeIndexRoute = adminHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginCodeRoute = authLoginCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => authLoginLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginLayoutRouteWithChildren
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/login/code': typeof authLoginCodeRoute
  '/home/': typeof adminHomeIndexRoute
  '/sse-test/': typeof adminSseTestIndexRoute
  '/stream-test/': typeof adminStreamTestIndexRoute
  '/websocket-test/': typeof adminWebsocketTestIndexRoute
  '/login/': typeof authLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/login/code': typeof authLoginCodeRoute
  '/home': typeof adminHomeIndexRoute
  '/sse-test': typeof adminSseTestIndexRoute
  '/stream-test': typeof adminStreamTestIndexRoute
  '/websocket-test': typeof adminWebsocketTestIndexRoute
  '/login': typeof authLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginLayoutRouteWithChildren
  '/(auth)/login-out': typeof authLoginOutRoute
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(auth)/login/code': typeof authLoginCodeRoute
  '/(admin)/home/': typeof adminHomeIndexRoute
  '/(admin)/sse-test/': typeof adminSseTestIndexRoute
  '/(admin)/stream-test/': typeof adminStreamTestIndexRoute
  '/(admin)/websocket-test/': typeof adminWebsocketTestIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/login/code'
    | '/home/'
    | '/sse-test/'
    | '/stream-test/'
    | '/websocket-test/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/login/code'
    | '/home'
    | '/sse-test'
    | '/stream-test'
    | '/websocket-test'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(auth)/login'
    | '/(auth)/login-out'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(auth)/login/code'
    | '/(admin)/home/'
    | '/(admin)/sse-test/'
    | '/(admin)/stream-test/'
    | '/(admin)/websocket-test/'
    | '/(auth)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  authLoginLayoutRoute: typeof authLoginLayoutRouteWithChildren
  authLoginOutRoute: typeof authLoginOutRoute
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-out': {
      id: '/(auth)/login-out'
      path: '/login-out'
      fullPath: '/login-out'
      preLoaderRoute: typeof authLoginOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/websocket-test/': {
      id: '/(admin)/websocket-test/'
      path: '/websocket-test'
      fullPath: '/websocket-test/'
      preLoaderRoute: typeof adminWebsocketTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/stream-test/': {
      id: '/(admin)/stream-test/'
      path: '/stream-test'
      fullPath: '/stream-test/'
      preLoaderRoute: typeof adminStreamTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/sse-test/': {
      id: '/(admin)/sse-test/'
      path: '/sse-test'
      fullPath: '/sse-test/'
      preLoaderRoute: typeof adminSseTestIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/home/': {
      id: '/(admin)/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof adminHomeIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/code': {
      id: '/(auth)/login/code'
      path: '/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof authLoginCodeRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminHomeIndexRoute: typeof adminHomeIndexRoute
  adminSseTestIndexRoute: typeof adminSseTestIndexRoute
  adminStreamTestIndexRoute: typeof adminStreamTestIndexRoute
  adminWebsocketTestIndexRoute: typeof adminWebsocketTestIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminHomeIndexRoute: adminHomeIndexRoute,
  adminSseTestIndexRoute: adminSseTestIndexRoute,
  adminStreamTestIndexRoute: adminStreamTestIndexRoute,
  adminWebsocketTestIndexRoute: adminWebsocketTestIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authLoginLayoutRouteChildren {
  authLoginCodeRoute: typeof authLoginCodeRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLoginLayoutRouteChildren: authLoginLayoutRouteChildren = {
  authLoginCodeRoute: authLoginCodeRoute,
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLoginLayoutRouteWithChildren = authLoginLayoutRoute._addFileChildren(
  authLoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  authLoginLayoutRoute: authLoginLayoutRouteWithChildren,
  authLoginOutRoute: authLoginOutRoute,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
