import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Locator, Page } from '@playwright/test';
import { expect } from '@playwright/test';

export interface DemoEntry {
  /** Visible title generated by the demo layout. */
  label: string;

  /** Demo directory name used by the route. */
  name: string;

  /** Tab value generated with the route list. */
  value: string;
}

interface DemoModuleCoverage {
  /** Demo route directory name. */
  name: string;

  /** Card titles that should be rendered for this demo route. */
  titles: string[];
}

const DEMO_APP_DIR = fileURLToPath(new URL('../src/app/[locale]/(demo)', import.meta.url));
const demoEntries = getDemoEntries();
const demoEntryByName = new Map(demoEntries.map(entry => [entry.name, entry]));

export const demoLocale = process.env.PLAYWRIGHT_LOCALE ?? 'zh';

export function getDemoEntries() {
  const source = readFileSync(new URL('../component-list.json', import.meta.url), 'utf-8');

  return JSON.parse(source) as DemoEntry[];
}

export function getDemoModuleCoverage() {
  return demoEntries.map<DemoModuleCoverage>(entry => {
    const routeDir = join(DEMO_APP_DIR, entry.name);
    const pagePath = join(routeDir, 'page.tsx');
    const pageSource = readSource(pagePath);
    const pageTitles = extractCardTitlesFromSource(pageSource);
    const moduleTitles = extractModuleCardTitles(routeDir, pageSource);
    const titles = Array.from(new Set([...pageTitles, ...moduleTitles]));

    return {
      name: entry.name,
      titles
    };
  });
}

export async function gotoDemo(page: Page, name: string) {
  const response = await page.goto(`/${demoLocale}/${name}`);
  const entry = demoEntryByName.get(name);

  expect(response?.ok()).toBe(true);

  if (entry) {
    await expect(page.getByRole('heading', { name: `${entry.label} Demo` })).toBeVisible();
  }
}

export function watchPageErrors(page: Page) {
  const errors: string[] = [];

  page.on('pageerror', error => {
    errors.push(error.message);
  });

  return errors;
}

export function expectNoPageErrors(errors: string[]) {
  expect(errors).toEqual([]);
}

export function demoCard(page: Page, title: string) {
  return page
    .locator('[data-slot="card-title"]')
    .filter({ hasText: exactText(title) })
    .first()
    .locator('xpath=ancestor::*[@data-slot="card-root"][1]');
}

export function demoCardContent(page: Page, title: string) {
  return demoCard(page, title).locator('[data-slot="card-content"]').first();
}

export function exactText(text: string) {
  return new RegExp(`^\\s*${escapeRegExp(text)}\\s*$`);
}

export async function expectTextVisible(scope: Page | Locator, text: string) {
  await expect(scope.getByText(exactText(text)).first()).toBeVisible();
}

function extractModuleCardTitles(routeDir: string, pageSource: string) {
  const modulesDir = join(routeDir, 'modules');

  if (!existsSync(modulesDir)) {
    return [];
  }

  const importedModuleFiles = [...pageSource.matchAll(/from ['"]\.\/modules\/([^'"]+)['"]/g)]
    .map(match => match[1])
    .map(modulePath => `${modulePath}.tsx`);

  return readdirSync(modulesDir)
    .filter(file => importedModuleFiles.includes(file))
    .flatMap(file => extractCardTitles(join(modulesDir, file)));
}

function extractCardTitles(filePath: string) {
  return extractCardTitlesFromSource(readSource(filePath));
}

function extractCardTitlesFromSource(source: string) {
  const titles = [...source.matchAll(/<Card\b[\s\S]*?title="([^"]+)"/g)].map(match => match[1]).filter(Boolean);

  return titles;
}

function readSource(filePath: string) {
  if (!existsSync(filePath)) {
    return '';
  }

  return readFileSync(filePath, 'utf-8');
}

function escapeRegExp(text: string) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
