export const SYSTEM_USER_URLS = {
  AUTH_ROLE: '/system/user/authRole',
  AUTH_ROLE_DETAIL: (userId: number | string) => `/system/user/authRole/${userId}`,
  CHANGE_STATUS: '/system/user/changeStatus',
  CREATE: '/system/user',
  DELETE: (userIds: Array<number | string>) => `/system/user/${userIds.map(String).join(',')}`,
  DETAIL: (userId: number | string) => `/system/user/${userId}`,
  DEPT_TREE: '/system/dept/deptTree',
  FORM_OPTIONS: '/system/user/',
  GET_USER_INFO: '/system/user/getInfo',
  IMPORT_DATA: '/system/user/importData',
  IMPORT_TEMPLATE: '/system/user/importTemplate',
  LIST_BY_DEPT: (deptId: number | string) => `/system/user/list/dept/${deptId}`,
  OPTIONS: '/system/user/optionselect',
  POST_OPTIONS: '/system/post/optionselect',
  RESET_PASSWORD: '/system/user/resetPwd',
  UPDATE: '/system/user',
  USER_EXPORT: '/system/user/export',
  USER_LIST: '/system/user/list'
} as const;
