/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const atom: typeof import('jotai').atom
  const createStore: typeof import('jotai').createStore
  const useAtom: typeof import('jotai').useAtom
  const useAtomValue: typeof import('jotai').useAtomValue
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useId: typeof import('react').useId
  const useMemo: typeof import('react').useMemo
  const useRef: typeof import('react').useRef
  const useSetAtom: typeof import('jotai').useSetAtom
  const useState: typeof import('react').useState
}
